!classDefinition: #Pepe category: #'Ejercicio 1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'Ejercicio 1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: '-- all --' stamp: 'Lu 8/19/2025 20:25:19'!
hola
"comentario"

^'Chau'! !
